import os
from app import app, db
from models import MenuItem, Category

guj_map = {
    "Garlic Bread": "ગાર્લિક બ્રેડ", "Mojito": "મોજિટો", "Shake": "શેક",
    "Plain Dosa": "પ્લેન ડોસા", "Masala Dosa": "મસાલા ડોસા", "Mesur Dosa": "મેસુર ડોસા",
    "Fancy Dosa": "ફેન્સી ડોસા", "Sandwich": "સેન્ડવીચ", "Burger": "બર્ગર",
    "Pizza": "પિઝા", "Dal Bati (Fix Plate)": "દાલ બાટી (ફિક્સ પ્લેટ)",
    "Started Chinese": "સ્ટાર્ટેડ ચાઈનીઝ", "Chinese Rice & Noodles": "ચાઈનીઝ રાઇસ એન્ડ નૂડલ્સ",
    "Started Tandoor": "સ્ટાર્ટેડ તંદૂર", "Soup": "સૂપ", "Rajasthani Tadka": "રાજસ્થાની તડકા",
    "Kaju Khajana": "કાજુ ખજાના", "Kofta": "કોફ્તા", "Dal & Rice": "દાલ એન્ડ રાઇસ",
    "Salad / Raita / Papad": "સલાડ / રાયતા / પાપડ", "Pulav & Biriyani": "પુલાવ એન્ડ બિરયાની",
    "Tandoori Roti & Naan": "તંદૂરી રોટી એન્ડ નાન", "Pau Bhaji": "પાવ ભાજી", "Extra": "એક્સ્ટ્રા",
    "Paneer Main Course": "પનીર મેઈન કોર્સ", "Veg. Panjabi (Khajana)": "વેજ. પંજાબી (ખજાના)",
    "Tava Roti Tikad & Khoba": "તવા રોટી ટિક્કડ એન્ડ ખોબા",
    "Butter Garlic Bread": "બટર ગાર્લિક બ્રેડ", "Jalapeno Cheese Garlic Bread": "જલાપીનો ચીઝ ગાર્લિક બ્રેડ",
    "Spicy Cheese Garlic Bread": "સ્પાઇસી ચીઝ ગાર્લિક બ્રેડ", "Creamy Cheese Garlic Bread": "ક્રીમી ચીઝ ગાર્લિક બ્રેડ",
    "Virgin Mojito": "વર્જિન મોજિટો", "Pineapple Mojito": "પાઈનેપલ મોજિટો",
    "Mango Mojito": "મેંગો મોજિટો", "Watermelon Mojito": "વોટરમેલન મોજિટો",
    "Pineapple Shake": "પાઈનેપલ શેક", "Kiwi Shake": "કીવી શેક", "Oreo Shake": "ઓરિયો શેક",
    "Kit Kat Shake": "કિટ કેટ શેક", "Mango Shake": "મેંગો શેક", "Paper Dosa": "પેપર ડોસા",
    "Baby Paper": "બેબી પેપર", "Butter Paper": "બટર પેપર", "Simple Paper": "સિમ્પલ પેપર",
    "Garlic Paper": "ગાર્લિક પેપર", "Cheese Paper": "ચીઝ પેપર", "Chocolate Paper": "ચોકલેટ પેપર",
    "Cheese Paneer Paper": "ચીઝ પનીર પેપર", "Butter Masala Dosa": "બટર મસાલા ડોસા",
    "Maggi Masala Dosa": "મેગી મસાલા ડોસા", "Masur Masala Dosa": "મેસુર મસાલા ડોસા",
    "Panner Masala Dosa": "પનીર મસાલા ડોસા", "Palak Paneer Masala Dosa": "પાલક પનીર મસાલા ડોસા",
    "Cheese Masala Dosa": "ચીઝ મસાલા ડોસા", "Mix Veg. Masala Dosa": "મિક્સ વેજ. મસાલા ડોસા",
    "Cheese Panner Masala Dosa": "ચીઝ પનીર મસાલા ડોસા", "Mesur Bhaji": "મેસુર ભાજી",
    "Butter Mesur": "બટર મેસુર", "Green Mesur": "ગ્રીન મેસુર", "Paneer Mesur": "પનીર મેસુર",
    "Cheese Mesur": "ચીઝ મેસુર", "Cheese Paneer Mesur": "ચીઝ પનીર મેસુર",
    "Chocolate Mesur": "ચોકલેટ મેસુર", "Green Gotala Mesur": "ગ્રીન ગોટાળા મેસુર",
    "Sp. Chamunda Mesure": "સ્પે. ચામુંડા મેસુર", "Maggi Dosa": "મેગી ડોસા",
    "Panner Maggi Dosa": "પનીર મેગી ડોસા", "Sweet Corn Dosa": "સ્વીટ કોર્ન ડોસા",
    "Chainiz Dosa": "ચાઈનીઝ ડોસા", "Jinni Roll": "જીન્ની રોલ", "Raja Rani": "રાજા રાની",
    "Spring Roll": "સ્પ્રિંગ રોલ", "Cheese Maggi Dosa": "ચીઝ મેગી ડોસા",
    "Paneer Sweet Corn Dosa": "પનીર સ્વીટ કોર્ન ડોસા", "Cheese Sweet Corn Dosa": "ચીઝ સ્વીટ કોર્ન ડોસા",
    "Paneer Chili Dosa": "પનીર ચીલી ડોસા", "Dil Khush Dosa": "દિલ ખુશ ડોસા",
    "Pizza Dosa": "પિઝા ડોસા", "Cheese Chili Dosa": "ચીઝ ચીલી ડોસા", "Matter Dosa": "મટર ડોસા",
    "Sp. Chamuda Dosa": "સ્પે. ચામુંડા ડોસા", "Veg. Sandwich": "વેજ. સેન્ડવીચ",
    "Veg. Green Sandwich": "વેજ. ગ્રીન સેન્ડવીચ", "Clab Sandwich": "ક્લબ સેન્ડવીચ",
    "Bombay Masala Sandwich": "બોમ્બે મસાલા સેન્ડવીચ", "Veg. Cheese Garlic Sandwich": "વેજ. ચીઝ ગાર્લિક સેન્ડવીચ",
    "Peri Peri Paneer Sandwich": "પેરી પેરી પનીર સેન્ડવીચ", "Paneer Tikka Sandwich": "પનીર ટિક્કા સેન્ડવીચ",
    "S.p. Sandwich": "સ્પે. સેન્ડવીચ", "Veg. Classic Burger": "વેજ. ક્લાસિક બર્ગર",
    "Hot N Spicy Burger": "હોટ એન્ડ સ્પાઇસી બર્ગર", "Veg. Cheese Burger": "વેજ. ચીઝ બર્ગર",
    "Crispy Allo Tikka Burger": "ક્રિસ્પી આલુ ટિક્કા બર્ગર", "Classic Panner Burger": "ક્લાસિક પનીર બર્ગર",
    "Classic Margherita": "ક્લાસિક માર્ગેરીટા", "o.t Pizza": "ઓ.ટી. પિઝા",
    "Farmhouse Pizza": "ફાર્મહાઉસ પિઝા", "Pizza La pizza": "પિઝા લા પિઝા",
    "Veggie Lover Pizza": "વેજી લવર પિઝા", "Veggie Peri Peri": "વેજી પેરી પેરી",
    "Sp. Pizza": "સ્પે. પિઝા", "Sp. Chamunda Dal-Bati": "સ્પે. ચામુંડા દાલ-બાટી",
    "Regular Dalbati": "રેગ્યુલર દાલ-બાટી", "Dalbati Plain": "દાલ-બાટી પ્લેન",
    "Rajasthani Kadhi Bati": "રાજસ્થાની કઢી બાટી", "Veg. Manchurian Dry": "વેજ. મંચુરિયન ડ્રાય",
    "Veg. Manchurian Greavy": "વેજ. મંચુરિયન ગ્રેવી", "Paneer Chilly Dry": "પનીર ચીલી ડ્રાય",
    "Veg. Schezwan Manchurian": "વેજ. શેઝવાન મંચુરિયન", "Paneer Chilly Greavy": "પનીર ચીલી ગ્રેવી",
    "Veg. Hakka Noodles": "વેજ. હક્કા નૂડલ્સ", "Singapori Noodles": "સિંગાપુરી નૂડલ્સ",
    "Chainiz Bhel": "ચાઈનીઝ ભેલ", "Fried Rice": "ફ્રાઈડ રાઇસ",
    "Singapori Fried Rice": "સિંગાપુરી ફ્રાઈડ રાઇસ", "Schezwan Noodles": "શેઝવાન નૂડલ્સ",
    "Bombay Bhal": "બોમ્બે ભેલ", "Paneer Tikka Dry.": "પનીર ટિક્કા ડ્રાય",
    "Hara Bhara Kabab": "હરા ભરા કબાબ", "Pudina Tikka Dry.": "ફુદીના ટિક્કા ડ્રાય",
    "Hot N Sour Soup": "હોટ એન્ડ સોર સૂપ", "Manshau Soup": "મનચાઉ સૂપ",
    "Cream Of Tomato Soup": "ક્રીમ ઓફ ટોમેટો સૂપ", "Lemon Coriander": "લેમન કોરીયેન્ડર",
    "Sp. Malai Besan gatta": "સ્પે. મલાઈ બેસન ગટ્ટા", "Besan Gatta (Regular)": "બેસન ગટ્ટા (રેગ્યુલર)",
    "Sp. Ker sangri": "સ્પે. કેર સાંગરી", "Sp. Kaju Gatiya": "સ્પે. કાજુ ગાંઠિયા",
    "Rabadi Masala": "રાબડી મસાલા", "Sev Tamatra": "સેવ ટમેટા", "Sev Masala": "સેવ મસાલા",
    "Sev Payaz": "સેવ પ્યાઝ", "Sev Bhaji milk": "સેવ ભાજી મિલ્ક", "Malai Payaz": "મલાઈ પ્યાઝ",
    "Allu Matter": "આલુ મટર", "Allu Gobi": "આલુ ગોભી", "Allu palak": "આલુ પાલક",
    "Papad Payaz": "પાપડ પ્યાઝ", "Sp. Lasaniya Bataka (katiyawadi)": "સ્પે. લસણીયા બટાકા",
    "Dahi Fry.": "દહી ફ્રાય", "Dahi Payaz Tomato": "દહી પ્યાઝ ટોમેટો",
    "Kaju Butter Masala": "કાજુ બટર મસાલા", "Kaju Cheese Masala": "કાજુ ચીઝ મસાલા",
    "Kaju Curry": "કાજુ કરી", "Kaju Masala (Spaicy)": "કાજુ મસાલા (સ્પાઇસી)",
    "Khoya Kaju": "ખોયા કાજુ", "Sp. Haldi Ka Sak (sigenebal)": "સ્પે. હલ્દી કા શાક",
    "Malai Kofta (Sweet)": "મલાઈ કોફ્તા (સ્વીટ)", "Kaju Kofta": "કાજુ કોફ્તા",
    "Paneer Kofta": "પનીર કોફ્તા", "Nargisi Kofta": "નરગીસી કોફ્તા", "Dal Fry": "દાલ ફ્રાય",
    "Dal Tadka": "દાલ તડકા", "Dal Fry with Butter": "દાલ ફ્રાય વિથ બટર", "Stem Rice": "સ્ટીમ રાઇસ",
    "Jeera Rice": "જીરા રાઇસ", "Masala Rice": "મસાલા રાઇસ", "Green Salad": "ગ્રીન સલાડ",
    "Tomato Salad": "ટોમેટો સલાડ", "Boondi Raita": "બુંદી રાયતા", "Veg. Raita": "વેજ. રાયતા",
    "Fry. Papad": "ફ્રાય પાપડ", "Rosted Papad": "રોસ્ટેડ પાપડ", "Masala Papad With Cheese": "મસાલા પાપડ વિથ ચીઝ",
    "Masala Papad": "મસાલા પાપડ", "Rosted Khiciya": "રોસ્ટેડ ખીચીયા", "Fry. Khiciya": "ફ્રાય ખીચીયા",
    "Masala Khiciya": "મસાલા ખીચીયા", "Masala Khiciya With Cheese": "મસાલા ખીચીયા વિથ ચીઝ",
    "Sp. Chamunda Pulav": "સ્પે. ચામુંડા પુલાવ", "Veg. Cheese Pulav": "વેજ. ચીઝ પુલાવ",
    "Veg. Hederabadi Pulav": "વેજ. હૈદરાબાદી પુલાવ", "Veg. Pulav": "વેજ. પુલાવ",
    "Veg. Paneer Pulav": "વેજ. પનીર પુલાવ", "Veg. Biriyani": "વેજ. બિરયાની",
    "Veg. Hederabadi Biriyani": "વેજ. હૈદરાબાદી બિરયાની", "Plain Tandoori Roti": "પ્લેન તંદૂરી રોટી",
    "Butter Tandoori Roti": "બટર તંદૂરી રોટી", "Lassa Paratha": "લચ્છા પરાઠા",
    "Butter Lassa Paratha": "બટર લચ્છા પરાઠા", "Plain Naan": "પ્લેન નાન", "Butter Naan": "બટર નાન",
    "Garlic Naan": "ગાર્લિક નાન", "Butter Kulcha": "બટર કુલચા", "Aloo Paratha (Lunch time)": "આલુ પરાઠા (લંચ ટાઈમ)",
    "Pau Bhaji Regular": "પાવ ભાજી રેગ્યુલર", "Butter Pau Bhaji": "બટર પાવ ભાજી",
    "Cheese Pau Bhaji": "ચીઝ પાવ ભાજી", "Sp. Chamunda Pau Bhaji": "સ્પે. ચામુંડા પાવ ભાજી",
    "Sp. Red Gotala Bhaji": "સ્પે. રેડ ગોટાળા ભાજી", "Sp. Green Gotala Bhaji": "સ્પે. ગ્રીન ગોટાળા ભાજી",
    "Masala Tukda Pau": "મસાલા ટુકડા પાવ", "Green Pau Bhaji Butter": "ગ્રીન પાવ ભાજી બટર",
    "Extra Cheese": "એક્સ્ટ્રા ચીઝ", "Ex. Pau Oil (3 Pcs)": "એક્સ્ટ્રા પાવ ઓઈલ",
    "Ex. Pau Butter (2 Pcs)": "એક્સ્ટ્રા પાવ બટર", "Bati 1 Pcs": "બાટી 1 પીસ",
    "Bati 1 Pcs Ghee": "બાટી 1 પીસ ઘી", "Churma Laddu 1 Pcs": "ચુરમા લાડુ 1 પીસ",
    "Churma 1 Plate": "ચુરમા 1 પ્લેટ", "Ghee (20Gm)": "ઘી (20 ગ્રામ)",
    "Dal Ex. 1 Katori": "દાલ એક્સ્ટ્રા 1 કટોરી", "Dal Ex. Full 1 Plate": "દાલ એક્સ્ટ્રા ફૂલ 1 પ્લેટ",
    "Plain Dahi Hafe": "પ્લેન દહીં હાફ", "Plain Dahi Full Plat": "પ્લેન દહીં ફૂલ પ્લેટ",
    "Water Botter": "વોટર બોટલ", "Coddlings": "કોલ્ડ્રિંક્સ", "Paneer Tika Masala": "પનીર ટિક્કા મસાલા",
    "Paneer Butter Masala": "પનીર બટર મસાલા", "Paneer Pasanda": "પનીર પસંદા",
    "Paneer Chatpata": "પનીર ચટપટા", "Paneer Lasniya": "પનીર લસણીયા", "Paneer Balti": "પનીર બાલ્ટી",
    "Paneer Tava": "પનીર તવા", "Paneer Handi": "પનીર હાંડી", "Cheese Anguri": "ચીઝ અંગૂરી",
    "Paneer Patiyala": "પનીર પટિયાલા", "Paneer Shahi": "પનીર શાહી", "Paneer Toofani": "પનીર તુફાની",
    "Paneer Angara": "પનીર અંગારા", "Paneer Bhurji": "પનીર ભુર્જી", "Palk Paneer Bhurji": "પાલક પનીર ભુર્જી",
    "Palk Paneer": "પાલક પનીર", "Mutter Paneer": "મટર પનીર", "Chna Paneer Masala": "ચના પનીર મસાલા",
    "Paneer Cheese Masala": "પનીર ચીઝ મસાલા", "Paneer kaju Masala": "પનીર કાજુ મસાલા",
    "Cheese Butter Masala": "ચીઝ બટર મસાલા", "Paneer Aachari": "પનીર અચારી", "Sp. Chamunda": "સ્પે. ચામુંડા",
    "Sp. Methi Makai Mattre": "સ્પે. મેથી મકાઈ મટર", "Veg. Handi": "વેજ. હાંડી", "Veg. kadai": "વેજ. કઢાઈ",
    "Vag. Jaipuri": "વેજ. જયપુરી", "Veg. Hedraldadi": "વેજ. હૈદરાબાદી", "Veg. Hariyali Mix": "વેજ. હરિયાળી મિક્સ",
    "Veg. kolapuri": "વેજ. કોલ્હાપુરી", "Mix Vegetable": "મિક્સ વેજીટેબલ", "MushRoom Butter Masala": "મશરૂમ બટર મસાલા",
    "Chana Masala": "ચના મસાલા", "Chana Paneer Masala": "ચના પનીર મસાલા", "Plain Palak": "પ્લેન પાલક",
    "Tava Chapati": "તવા ચપાતી", "Butter Tava Chapadi": "બટર તવા ચપાતી", "Plain Parratha": "પ્લેન પરાઠા",
    "Butter Parratha": "બટર પરાઠા", "Marwadi Tikkad Roti (Ghee)": "મારવાડી ટિક્કડ રોટી (ઘી)",
    "Khoba Roti (Ghee)": "ખોબા રોટી (ઘી)", "Aloo parrtha Tava (Lunch)": "આલુ પરાઠા તવા (લંચ)",
    "Paneer Parratha Tava": "પનીર પરાઠા તવા", "Bajri na Rotala (Shegnebul)": "બાજરી ના રોટલા",
    "Extra Ghee (20 gm.)": "એક્સ્ટ્રા ઘી (20 ગ્રામ)"
}

with app.app_context():
    for item in MenuItem.query.all():
        if item.name in guj_map:
            item.name_gu = guj_map[item.name]
    for cat in Category.query.all():
        if cat.name in guj_map:
            cat.name_gu = guj_map[cat.name]
    db.session.commit()
    print("Gujarati text updated directly to Neon DB!")
